name: Build libjpeg-turbo for Android

on:
  workflow_dispatch:   # 手动触发

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [ armeabi-v7a, arm64-v8a, x86, x86_64 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装 CMake
        uses: lukka/get-cmake@v3.28.3

      - name: 安装 Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 25.2.9519653

      - name: 配置 CMake
        run: |
          cmake -S third_party/libjpeg-turbo -B build/${{ matrix.abi }} \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-21 \
            -DENABLE_SHARED=TRUE \
            -DENABLE_STATIC=FALSE \
            -DWITH_TURBOJPEG=TRUE

      - name: 编译
        run: cmake --build build/${{ matrix.abi }} --config Release -j$(nproc)

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.abi }}
          path: build/${{ matrix.abi }}
