name: Build libjpeg-turbo (Android + iOS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # =========================
  # Android 构建任务
  # =========================
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [ armeabi-v7a, arm64-v8a, x86, x86_64 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装 CMake
        uses: lukka/get-cmake@v3.28.3

      - name: 安装 Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 26.1.10909125

      - name: 配置 CMake
        run: |
          cmake -S third_party/libjpeg-turbo -B build/${{ matrix.abi }} \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-21 \
            -DENABLE_SHARED=TRUE \
            -DENABLE_STATIC=FALSE \
            -DWITH_TURBOJPEG=TRUE

      - name: 编译
        run: cmake --build build/${{ matrix.abi }} --config Release -j$(nproc)

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.abi }}
          path: build/${{ matrix.abi }}

  # =========================
  # iOS 构建任务
  # =========================
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装依赖
        run: brew install cmake ninja nasm

      - name: 配置 CMake (iOS arm64)
        run: |
          cmake -S third_party/libjpeg-turbo -B build/ios-arm64 \
            -G Ninja \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DENABLE_SHARED=FALSE \
            -DENABLE_STATIC=TRUE \
            -DWITH_TURBOJPEG=TRUE

      - name: 编译
        run: cmake --build build/ios-arm64 --config Release -j$(sysctl -n hw.ncpu)

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: ios-arm64
          path: build/ios-arm64