name: Build libjpeg-turbo for Android (arm64-v8a, local NDK)

on:
  workflow_dispatch:   # 手动触发

jobs:
  android-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装依赖
        run: sudo apt-get update && sudo apt-get install -y wget unzip ninja-build

      - name: 下载并解压 NDK r25c
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O ndk.zip
          unzip -q ndk.zip -d $HOME
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r25c" >> $GITHUB_ENV

      - name: 安装 CMake
        uses: lukka/get-cmake@v3.28.3

      - name: 配置 CMake (arm64-v8a, 静态库)
        run: |
          cmake -S . -B build/arm64-v8a \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DENABLE_SHARED=FALSE \   # 关闭动态库
            -DENABLE_STATIC=TRUE \    # 打开静态库
            -DWITH_TURBOJPEG=TRUE

      - name: 编译
        run: cmake --build build/arm64-v8a --config Release -j$(nproc)

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-v8a
          path: build/arm64-v8a



